CREATE TABLE Accounts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(60) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    CreditCardNumber VARCHAR(30) NOT NULL,
    CVV VARCHAR(10) NOT NULL
);